### ISSUE TITLE
Brave initial_preferences docs

### ISSUE THREAD

**Issue by EXXodos911** [cristhian2k47/initial_preferences#1]
Do you know if theres documentation of all the brave specific settings for initial_preferences?

**Comment by cristhian2k47** [comment]
which options do you want to know?

**Comment by cristhian2k47** [comment]
type in tour brave browser:
brave://prefs-internals

**Comment by cristhian2k47** [comment]
no but what i do is i go into brave://prefs-internals and save the file, then i go to settings and change an option and compare changes between both files

**Comment by cristhian2k47** [comment]
yes:
cristhian2k47
